### ISSUE TITLE
Use Environment Variables in Sonar Job Name Field

### ISSUE THREAD

**Issue by emoshaya** [andnyb/sonar-slack-pusher#14]
It's a shame the Sonar Job Name field does not accept environment variables. We have 40+ parameterised jobs inheriting from a template. The plugin needs to accept environment variables in the fields in order for to integrate it within out templates. Please update to allow for this...

Thanks

![slack](https://cloud.githubusercontent.com/assets/8818542/14853361/1f59e1ba-0c83-11e6-8504-d57c571a3918.png)

**Comment by andnyb** [comment]
Added the 'shamelessly' missing feature, should have had it from the start. Release here: https://github.com/andnyb/sonar-slack-pusher/releases/tag/1.6

**Comment by emoshaya** [comment]
That is fantastic!!! Does this work for the additional channel too? or just the sonar job name?

**Comment by andnyb** [comment]
Sure it can be added, it is the testing that takes time. Additional is a bit misleading, the notification only ends up in one channel, the default or the one given in additional. Have not really used that feature.

**Comment by emoshaya** [comment]
It would still be nice to have the channel parametrised as each job will publish to a separate slack channel based on the project type.

**Comment by andnyb** [comment]
Done, https://github.com/andnyb/sonar-slack-pusher/releases/tag/1.7

**Comment by emoshaya** [comment]
Many Thanks :+1:
