### ISSUE TITLE
api/resources is deprecated since SonarQube 5.6

### ISSUE THREAD

**Issue by callain** [andnyb/sonar-slack-pusher#20]
Hello,

The following API call that you use is deprecated since SonarQube 5.6 :

`String path = "/api/resources?metrics=alert_status,quality_gate_details&includealerts=true";`

```
16:44:16 [ssp] Calling SonarQube on: http://localhost:9000/api/resources?metrics=alert_status,quality_gate_details&includealerts=true
16:44:16 [ssp] Got a non 200 response from SonarQube. Server responded with '404 : '
16:44:16 [ssp] Could not get SonarQube results, exception: 'Got a non 200 status code from SonarQube!'
16:44:16 Build step 'SonarQube Slack pusher' marked build as failure
```

Because the server response is a 404, the plugin marks the build as fail.

Do you consider updating your plugin ?

**Comment by andnyb** [comment]
Yes, looking at it. It is a totally different call with a very non-informal response that needs to be dealt with to make sense in a Slack message.

**Comment by andnyb** [comment]
Try the top one... https://github.com/jenkinsci/sonarqube-slack-pusher-plugin/releases

**Comment by callain** [comment]
Thank you, the build success
```
18:09:08 [ssp] Calling SonarQube on: http://localhost:9000/api/qualitygates/project_status?projectKey=xx:xx
18:09:08 [ssp] No failed quality checks found for project 'xx:xx' nothing to report to the 'default' Slack channel.
```
My project is empty so there is nothing to report, I will try tomorrow with some rules breaking code.
Maybe you can add a green report in this case ?

**Comment by callain** [comment]
With rules breaking code

```
11:55:36 [ssp] Calling SonarQube on: http://localhost:9000/api/qualitygates/project_status?projectKey=repriselbp:sidomi
11:55:36 Build step 'SonarQube Slack pusher' marked build as failure
```

Sadly, no message in my slack channel

**Comment by andnyb** [comment]
Ok, can you please put http://localhost:9000/api/qualitygates/project_status?projectKey=repriselbp:sidomi in your browser and paste the obfuscated response here please so that I can debug that part. Might need to add some trace regarding the response if it is anything but 200.

**Comment by callain** [comment]
Yes, here is an example

```
{
	"projectStatus": {
		"status": "ERROR",
		"conditions": [{
			"status": "OK",
			"metricKey": "new_security_rating",
			"comparator": "GT",
			"periodIndex": 1,
			"errorThreshold": "1",
			"actualValue": "1"
		}, {
			"status": "OK",
			"metricKey": "new_reliability_rating",
			"comparator": "GT",
			"periodIndex": 1,
			"errorThreshold": "1",
			"actualValue": "1"
		}, {
			"status": "OK",
			"metricKey": "new_maintainability_rating",
			"comparator": "GT",
			"periodIndex": 1,
			"errorThreshold": "1",
			"actualValue": "1"
		}, {
			"status": "ERROR",
			"metricKey": "new_coverage",
			"comparator": "LT",
			"periodIndex": 1,
			"errorThreshold": "80",
			"actualValue": "0.0"
		}],
		"periods": [{
			"index": 1,
			"mode": "previous_version",
			"date": "2017-05-05T17:17:52+0200"
		}]
	}
}
```

**Comment by andnyb** [comment]
https://github.com/jenkinsci/sonarqube-slack-pusher-plugin/releases/tag/v2.0-beta

Fixed, sorry simple indexing mistake on my side. Just grab the new hpi from the link above.

**Comment by callain** [comment]
```
SonarQube Slack Pusher APP [1:58 PM] 
*SonarQube job*
*Job:* xxx:xxx
*Branch:*
*DANGER*
*Reason:*
- new_coverage '0.0' < '80' over 'null' previous_version
```

It works ! 🙂
