### ISSUE TITLE
[ssp] no failed quality checks for project 'project-name null' nothing to report to the Slack channel.

### ISSUE THREAD

**Issue by dpitera** [andnyb/sonar-slack-pusher#5]
I am getting this error after I follow the steps here: https://technicaltesting.wordpress.com/2015/06/17/sonarqube-quality-gate-feedback-in-a-slack-channel/

Can you provide a working example, including the link to the sonarqube server, so I can see the project-name. I first tried not supplying a branch name; then I tried master. But I can't seem to get it to work....

**Comment by andnyb** [comment]
The link to the SonarQube server is now in the plugin trace when running it.
