### ISSUE TITLE
Config for user and password

### ISSUE THREAD

**Issue by jllado** [andnyb/sonar-slack-pusher#6]
I would be great if we can specify user and password for sonar ^^

**Comment by cteyton** [comment]
+1

**Comment by mastong** [comment]
:+1: 

I would like to use this plugin in my work, but we need a user/password to connect to our Sonar.
And so, when the plugin runs, we've got the error message : 
[ssp] got a non 200 response from Sonar at URL: 'http://xxxxxx:9000/api/resources?metrics=qi-quality-index,coverage,test_success_density,blocker_violations,critical_violations&includealerts=true'

**Comment by andnyb** [comment]
OK , finally got the time to get this done. Basic auth added to 1.5 @ https://github.com/andnyb/sonar-slack-pusher/releases/tag/1.5.
